- name: Update system
  apt: update_cache=yes

- name: Install modules jdk
  apt:
    name: default-jdk
    state: present
    
- name: Install modules python3
  apt:
    name: python3
    state: present

- name: install pip3
  apt: name=python3-pip state=present

- name: Install modules boto3
  pip:
    name: "{{ item }}"
  with_items:
    - boto3
    - botocore

- name: Create directory
  file:
    path: /home/boxfuse-sample-java-war-hello
    state: directory

- name: Clone boxfuse
  git:
    repo: 'https://github.com/boxfuse/boxfuse-sample-java-war-hello.git'
    dest: /home/boxfuse-sample-java-war-hello/

- name: install maven
  become: yes
  apt:
    pkg: maven
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - maven

- name: Build boxfuse
  command: 'mvn package'
  args:
    chdir: /home/boxfuse-sample-java-war-hello/

- name: Simple PUT operation
  aws_s3:
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    bucket: mybacket29.kupa.com
    object: hello-1.0.war
    src: /home/boxfuse-sample-java-war-hello/target/hello-1.0.war
    mode: put

