---
- hosts: localhost
  remote_user: root
  vars:
    keypair: mykey325
    instance_type: t2.micro
    security_group: MyGroup325
    image: ami-04505e74c0741db8d
    region: us-east-1

  tasks:
  - name: create a security group in AWS
    ec2_group:
      name: MyGroup325
      description: allow 22 port
      region: "{{ region }}"
      rules:
        - proto: tcp
          ports:
            - 22
          cidr_ip: 0.0.0.0/0

  - name: Create an EC2 key
    ec2_key:
      name: mykey325
      region: "{{ region }}"
    register: ec2_key

  - name: save private key
    copy:
      content: "{{ ec2_key.key.private_key }}"
      dest: "~/.ssh/id_rsa.pem"
      mode: 0600
    when: ec2_key.changed

  - name: create instance 1
    ec2:
      key_name: "{{ keypair }}"
      group: "{{ security_group }}"
      region: "{{ region }}"
      instance_type: "{{ instance_type }}"
      image: "{{ image }}"
      wait: yes
      wait_timeout: 500
      volumes:
        - device_name: /dev/sdh
          volume_size: 15
      instance_tags:
          Environment: Test
          Name: runbuild
      count: 1
    register: ec2

  - name: Add new instance 1 to host group
    add_host:
      hostname: "{{ item.public_ip }}"
      groupname: runbuild
    loop: "{{ ec2.instances }}"

  - name: Wait for SSH to come up
    delegate_to: "{{ item.public_dns_name }}"
    wait_for_connection:
      delay: 60
      timeout: 320
    loop: "{{ ec2.instances }}"

  - name: create instance 2
    ec2:
      key_name: "{{ keypair }}"
      group: "{{ security_group }}"
      region: "{{ region }}"
      instance_type: "{{ instance_type }}"
      image: "{{ image }}"
      wait: yes
      wait_timeout: 500
      volumes:
        - device_name: /dev/sdh
          volume_size: 15
      instance_tags:
          Environment: MyTest
          Name: MyTestApp
      count: 1
    register: ec2

  - name: Add new instance 2 to host group
    add_host:
      hostname: "{{ item.public_ip }}"
      groupname: testapp
    loop: "{{ ec2.instances }}"

  - name: Wait for SSH to come up
    delegate_to: "{{ item.public_dns_name }}"
    wait_for_connection:
      delay: 60
      timeout: 320
    loop: "{{ ec2.instances }}"

- name: package boxfuse
  hosts: runbuild
  remote_user: root
  become: true
  roles:
    - builder

- name: run boxfuse
  hosts: testapp
  remote_user: root
  become: true

  vars:
    ip_db:  runbuild

  roles:
    - runner