---
- hosts: localhost
  remote_user: root
  vars:
    keypair: mykey3
    instance_type: t2.micro
    security_group: MyGroup32
    image: ami-04505e74c0741db8d
    region: us-east-1

  tasks:
  - name: Create a security group in AWS
    ec2_group:
      name: "{{ security_group }}"
      description: allow 22 port
      region: "{{ region }}"
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 8080
          to_port: 8080
          cidr_ip: 0.0.0.0/0

  - name: Create an EC2 key
    ec2_key:
      name: "{{ keypair }}"
      region: "{{ region }}"
    register: ec2_key
    
  - name: Save private key
    copy:
      content: "{{ ec2_key.key.private_key }}"
      dest: "{{ ansible_env.HOME }}/.ssh/{{ keypair }}.pem"
      mode: 0600
    when: ec2_key.changed

  - name: Save secret key to builder
    copy:
      src: /home/key/main.yml
      dest: /home/13/roles/builder/defaults/

  - name: Save secret key to runner
    copy:
      src: /home/key/main.yml
      dest: /home/13/roles/runner/defaults/

  - name: Create instance 1
    ec2:
      key_name: "{{ keypair }}"
      group: "{{ security_group }}"
      region: "{{ region }}"
      instance_type: "{{ instance_type }}"
      image: "{{ image }}"
      wait: yes
      volumes:
        - device_name: /dev/sdh
          volume_size: 15
      instance_tags:
          Name: TestBuild
      count: 1
    register: ec2

  - name: Add new instance 1 to host group
    add_host:
      hostname: "{{ item.public_ip }}"
      ansible_private_key_file: ~/.ssh/{{ keypair }}.pem
      groupname: runbuild
      region: "{{ region }}"
    loop: "{{ ec2.instances }}"

    # - name: Wait for SSH to come up
    #   delegate_to: "{{ item.public_dns_name }}"
    #   wait_for_connection:
    #     delay: 65
    #     timeout: 120
    #   loop: "{{ ec2.instances }}"

  - name: Create instance 2
    ec2:
      key_name: "{{ keypair }}"
      group: "{{ security_group }}"
      region: "{{ region }}"
      instance_type: "{{ instance_type }}"
      image: "{{ image }}"
      wait: yes
      wait_timeout: 500
      volumes:
        - device_name: /dev/sdh
          volume_size: 15
      instance_tags:
          Environment: MyTest
          Name: MyTestApp
      count: 1
    register: ec2

  - name: Add new instance 2 to host group
    add_host:
      hostname: "{{ item.public_ip }}"
      ansible_private_key_file: ~/.ssh/{{ keypair }}.pem
      groupname: testapp
    loop: "{{ ec2.instances }}"

 # - name: Wait for SSH to come up
 #   delegate_to: "{{ item.public_dns_name }}"
 #   wait_for_connection:
 #     delay: 65
 #     timeout: 120
 #   loop: "{{ ec2.instances }}"

#  - name: Wait for SSH to come up
#    wait_for:
#      host: "{{ item.public_ip }}"
#      port: 22
#      state: started
#    with_items: "{{ ec2.instances }}"

- name: Package boxfuse
  hosts: runbuild
  remote_user: ubuntu
  become_user: root
  become: true
  roles:
    - builder

- name: Run boxfuse
  hosts: testapp
  remote_user: ubuntu
  become: yes
  become_user: root

  roles:
    - runner
