---
- name: package boxfuse
  hosts: db
  remote_user: root
  become: true

  roles:
    - builder
    
- name: run boxfuse
  hosts: web
  remote_user: root
  become: true

  vars:
    ip_db:  51.250.24.96

  roles:
    - runner
    

