---
- hosts: localhost
  remote_user: root

  tasks:
  - name: create a security group in AWS
    ec2_group:
      name: MyGroup325
      description: allow 22 port
      region: us-east-1
      rules:
        - proto: tcp
          ports:
            - 22
          cidr_ip: 0.0.0.0/0

  - name: Create an EC2 key
    ec2_key:
      name: mykey325
      region: eu-west-1
    register: ec2_key

  - name: save private key
    copy:
      content: "{{ ec2_key.key.private_key }}"
      dest: "~/.ssh/id_rsa.pem"
      mode: 0600
    when: ec2_key.changed

  - name: create instance
    ec2:
      key_name: mykey325
      group: MyGroup325
      region: eu-west-1
      instance_type: t2.micro
      image: ami-04505e74c0741db8d
      vpc_subnet_id: subnet-29e63245
      volumes:
        - device_name: /dev/sdh
          volume_size: 15
      assign_public_ip: yes
      count_tag:
        Name: dbserver
      exact_count: 2

  #- name: package boxfuse
  #  hosts: db
  #  remote_user: root
  #  become: true

  #  roles:
  #    - builder

  #- name: run boxfuse
  #  hosts: web
  #  remote_user: root
  #  become: true

  #  vars:
  #    ip_db:  84.201.165.201

  #  roles:
  #    - runner


