- name: Update system
  apt: update_cache=yes

- name: install JDK 11
  apt:
    name: openjdk-11-jdk
    state: present
    
- name: Install modules
  apt:
    name: python3
    state: present

- name: install pip3
  apt: name=python3-pip state=present

- name: Install modules boto3
  pip:
    name: "{{ item }}"
  with_items:
    - boto3
    - botocore

- name: Install Tomcat 9
  apt: name={{ item }} state=present
  with_items:
    - tomcat9

- name: Ensure Tomcat 9 service is started
  service:
    name: tomcat9
    state: started

- name: Simple GET operation
  aws_s3:
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    bucket: mybacket29.kupa.com
    object: hello-1.0.war
    dest: /var/lib/tomcat9/webapps/
    mode: get
