- name: Update system
  apt: update_cache=yes

- name: install JDK 11
  apt:
    name: openjdk-11-jdk
    state: present
    
- name: Install modules
  apt:
    name: python3
    state: present

- name: Install modules boto3
  pip:
    name: "{{ item }}"
  with_items:
    - boto3
    - botocore
  delegate_to: "{{ item.public_ip }}"

- name: Install Tomcat 9
  apt: name={{ item }} state=present
  with_items:
    - tomcat9

- name: Ensure Tomcat 9 service is started
  service:
    name: tomcat9
    state: started

- name: Copy key
  synchronize: src=/home/key/ dest=/home/13/roles/builder/defaults/
  delegate_to: localhost

- name: Simple GET operation
  aws_s3:
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    bucket: mybacket29.kupa.com
    object: hello-1.0.war
    dest: /var/lib/tomcat9/webapps/
    mode: get
