- name: Update system
  apt: update_cache=yes

- name: install JDK 11
  apt:
    name: openjdk-11-jdk
    state: present
    
- name: Install modules
  apt:
    name: python3
    state: present
    
- name: Install Tomcat 9
  apt: name={{ item }} state=present
  with_items:
    - tomcat9

- name: Ensure Tomcat 9 service is started
  service:
    name: tomcat9
    state: started
    
- name: Simple GET operation
  aws_s3:
    bucket: mybacket29.kupa.com
    object: hello-1.0.war
    dest: /var/lib/tomcat9/webapps/
    mode: get
