- name: Update system
  apt: update_cache=yes

- name: install JDK 11
  apt:
    name: openjdk-11-jdk
    state: present
    
- name: Install Tomcat 9
  apt: name={{ item }} state=present
  with_items:
    - tomcat9

- name: Ensure Tomcat 9 service is started
  service:
    name: tomcat9
    state: started

- name: Copy boxfuse
  synchronize: src=/home/boxfuse-sample-java-war-hello/target/ dest=/var/lib/tomcat9/webapps/
  delegate_to: "{{ ip_db }}"
  notify:
    - restart tomcat
